### ISSUE TITLE
Cannot sign up for slack account

### ISSUE THREAD

**Issue by atimmer** [phpnl/phpnl#7]
I cannot sign up for a slack account, see:
![screen shot 2015-04-22 at 09 54 58](https://cloud.githubusercontent.com/assets/584693/7269607/aed5d9ca-e8d5-11e4-89f9-eded904d8919.png)

The button just says "Error occurred"

**Comment by jaytaph** [comment]
Strange. I checked and it gives me an invitation email. What was the email you tried?

**Comment by atimmer** [comment]
services@atimmer.com

**Comment by jaytaph** [comment]
Seems that this email address was already invited. It will throw an error in that case. I've resend the invitation email to the email address, and you should be able to join the slack team.
